// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mode
int mode(IntegerVector v);
RcppExport SEXP home6_mode(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type v(vSEXP);
    __result = Rcpp::wrap(mode(v));
    return __result;
END_RCPP
}
// simplify2array
RObject simplify2array(List x);
RcppExport SEXP home6_simplify2array(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    __result = Rcpp::wrap(simplify2array(x));
    return __result;
END_RCPP
}
// ass
NumericMatrix ass(int n);
RcppExport SEXP home6_ass(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(ass(n));
    return __result;
END_RCPP
}
// test
double test(double min, double max);
RcppExport SEXP home6_test(SEXP minSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type min(minSEXP);
    Rcpp::traits::input_parameter< double >::type max(maxSEXP);
    __result = Rcpp::wrap(test(min, max));
    return __result;
END_RCPP
}
