# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title mode
#' @description This function determine the most frequently occurring value in an integer vector (mode). If the mode is ambiguous (e.g. for 1, 2, 2, 2, 3, 3, 1, 3), return any mode
#'
#' @param v - integer vector
#' @return integer value
#'
#' @export
mode <- function(v) {
    .Call('home6_mode', PACKAGE = 'home6', v)
}

#' @title simplify2array
#' @description This function filled  matrix by vectors column-by-column.
#'
#' @param x - list of numeric vectors
#' @return matrix 
#'
#' @export
simplify2array <- function(x) {
    .Call('home6_simplify2array', PACKAGE = 'home6', x)
}

#' @title ass
#' @description This funciotn for some given integer n generates all possible 0-1 assignment vectors of 2n survey participants in such a way that exactly n of them are assigned to group 0 (control) and the other n ones are assigned to group 1 (treatment)
#'
#' @param n - integer value
#' @return matrix with 2n columns and an appropriate number of rows
#'
#' @export
ass <- function(n) {
    .Call('home6_ass', PACKAGE = 'home6', n)
}

#' @title ...
#' @description ...
#'
#' @param min ...
#' @param max ....
#' @return ....
#'
#' @export
test <- function(min = 0.0, max = 1.0) {
    .Call('home6_test', PACKAGE = 'home6', min, max)
}

